### PR TITLE
Add an optional settings parameter to add()

### PR DESCRIPTION
**Pull request by camfraser**
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#Cue_settings

Thanks for making this module, @lmammino !

### CODE REVIEW

**Comment by camfraser** [comment]
Note that I did not update the `dist/` folder because the build step added some wonky spaces and it doesn't seem to update `vtt.min.js` file.

**Comment by lmammino** [comment]
That's a great addition :)

There are a couple of things that I would like to have (like the opportunity to support key-value objects for the options and add node 7 and node 8 in the CI), but I think this is good to go for now. I will merge and publish a new release.

Thanks a million for your contribution!

Are you using this library in some production product?

**Comment by camfraser** [comment]
That's great--thanks for hopping on it so quickly. I am using it in a production product, but unfortunately it is internal. I am using it to provide a front-end VTT editing feature for captions already produced by a third-party service.

**Comment by lmammino** [comment]
Lovely, glad to know that this library is being used in a serious project. I originally built it just to have captions in a test project i was doing some time ago.

I will try to invest some time during the next week to polish the build process and coding standards. Meanwhile feel more than welcome to contribute with PRs or issues if you feel there's some other important feature missing

**Pull request merged**
